apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: eckbbqkibana
spec:
  config:
    xpack.security.authc.providers.basic.basic1.order: 0
    xpack.fleet.agents.elasticsearch.hosts: ["https://eckbbqpi-es-http.default.svc:9200"]
    xpack.fleet.agents.fleet_server.hosts: ["https://fleet-server-agent-http.default.svc:8220"]
    xpack.fleet.packages:
      - name: system
        version: latest
      - name: elastic_agent
        version: latest
      - name: fleet_server
        version: latest
    xpack.fleet.agentPolicies:
      - name: Fleet Server on ECK policy
        id: eck-fleet-server
        namespace: default
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        package_policies:
        - name: fleet_server-1
          id: fleet_server-1
          package:
            name: fleet_server
      - name: Elastic Agent on ECK policy
        id: eck-agent
        namespace: default
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        package_policies:
          - name: system-1
            id: system-1
            package:
              name: system
  count: 1
  elasticsearchRef:
    name: eckbbqpi
  monitoring:
    logs:
      elasticsearchRefs:
      - name: eckbbqpi
    metrics:
      elasticsearchRefs:
      - name: eckbbqpi
  podTemplate:
    spec:
      containers:
      - env:
        - name: NODE_OPTIONS
          value: --max-old-space-size=2048
        name: kibana
        resources:
          limits:
            cpu: 3
            memory: 6Gi
          requests:
            cpu: 1
            memory: 2Gi
  version: 8.9.0